<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ShipmentsTableSeeder extends Seeder
{
    public function run(): void
    {
        $shipments = [
            [
                'no_invoice' => 'INV-001',
                'status' => 'Pesanan Diterima',
                'order_date' => Carbon::now()->subDays(10),
                'shipped_date' => null,
                'delivered_date' => null,
                'recipient_name' => 'Ahmad',
                'shipping_address' => 'Jl. Merdeka No.1, Jakarta',
                'tracking_number' => null,
                'courier' => 'JNE',
                'note' => 'Segera dikirim setelah packing',
                'total_payment' => 199000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_invoice' => 'INV-002',
                'status' => 'Sedang Diproses',
                'order_date' => Carbon::now()->subDays(9),
                'shipped_date' => null,
                'delivered_date' => null,
                'recipient_name' => 'Budi',
                'shipping_address' => 'Jl. Sudirman No.10, Bandung',
                'tracking_number' => null,
                'courier' => 'SiCepat',
                'note' => 'Pengecekan stok sedang dilakukan',
                'total_payment' => 250000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_invoice' => 'INV-003',
                'status' => 'Siap Dikirim',
                'order_date' => Carbon::now()->subDays(8),
                'shipped_date' => null,
                'delivered_date' => null,
                'recipient_name' => 'Citra',
                'shipping_address' => 'Jl. Asia Afrika No.5, Surabaya',
                'tracking_number' => null,
                'courier' => 'J&T',
                'note' => 'Packing selesai, menunggu kurir',
                'total_payment' => 320000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_invoice' => 'INV-004',
                'status' => 'Dalam Pengiriman',
                'order_date' => Carbon::now()->subDays(7),
                'shipped_date' => Carbon::now()->subDays(6),
                'delivered_date' => null,
                'recipient_name' => 'Dewi',
                'shipping_address' => 'Jl. Thamrin No.12, Jakarta',
                'tracking_number' => 'JNE123456789',
                'courier' => 'JNE',
                'note' => 'Barang sudah dikirim',
                'total_payment' => 275000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_invoice' => 'INV-005',
                'status' => 'Dalam Perjalanan',
                'order_date' => Carbon::now()->subDays(6),
                'shipped_date' => Carbon::now()->subDays(5),
                'delivered_date' => null,
                'recipient_name' => 'Eko',
                'shipping_address' => 'Jl. Pemuda No.22, Semarang',
                'tracking_number' => 'SICEPAT987654321',
                'courier' => 'SiCepat',
                'note' => 'Kurir sedang mengantarkan',
                'total_payment' => 310000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_invoice' => 'INV-006',
                'status' => 'Terkirim',
                'order_date' => Carbon::now()->subDays(10),
                'shipped_date' => Carbon::now()->subDays(9),
                'delivered_date' => Carbon::now()->subDays(1),
                'recipient_name' => 'Fajar',
                'shipping_address' => 'Jl. Diponegoro No.3, Yogyakarta',
                'tracking_number' => 'J&T456789123',
                'courier' => 'J&T',
                'note' => 'Paket diterima dengan baik',
                'total_payment' => 280000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_invoice' => 'INV-007',
                'status' => 'Terkirim',
                'order_date' => Carbon::now()->subDays(12),
                'shipped_date' => Carbon::now()->subDays(11),
                'delivered_date' => Carbon::now()->subDays(2),
                'recipient_name' => 'Gita',
                'shipping_address' => 'Jl. Gatot Subroto No.7, Medan',
                'tracking_number' => 'JNE987654321',
                'courier' => 'JNE',
                'note' => 'Diterima oleh penerima',
                'total_payment' => 340000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_invoice' => 'INV-008',
                'status' => 'Dibatalkan',
                'order_date' => Carbon::now()->subDays(5),
                'shipped_date' => null,
                'delivered_date' => null,
                'recipient_name' => 'Hendra',
                'shipping_address' => 'Jl. Sultan Agung No.15, Malang',
                'tracking_number' => null,
                'courier' => null,
                'note' => 'Pelanggan membatalkan pesanan',
                'total_payment' => 200000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_invoice' => 'INV-009',
                'status' => 'Pesanan Diterima',
                'order_date' => Carbon::now()->subDays(3),
                'shipped_date' => null,
                'delivered_date' => null,
                'recipient_name' => 'Intan',
                'shipping_address' => 'Jl. Mangga Dua No.9, Jakarta',
                'tracking_number' => null,
                'courier' => 'J&T',
                'note' => 'Menunggu diproses',
                'total_payment' => 150000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_invoice' => 'INV-010',
                'status' => 'Siap Dikirim',
                'order_date' => Carbon::now()->subDays(2),
                'shipped_date' => null,
                'delivered_date' => null,
                'recipient_name' => 'Joko',
                'shipping_address' => 'Jl. Kertajaya No.11, Surabaya',
                'tracking_number' => null,
                'courier' => 'SiCepat',
                'note' => 'Packing hampir selesai',
                'total_payment' => 270000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('shipments')->insert($shipments);
    }
}
